apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageclass-accessor-deployment
  namespace: default # NOTE: change the namespace
  labels:
    app: storageclass-accessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storageclass-accessor
  template:
    metadata:
      labels:
        app: storageclass-accessor
    spec:
      containers:
      - name: storageclass-accessor
        image: f10atin9/storageclass-accessor:v1.0 # change the image if you wish to use your own custom validation server image
        imagePullPolicy: IfNotPresent
        args: ['--tls-cert-file=/etc/storageclass-accessor-webhook/certs/cert.pem', '--tls-private-key-file=/etc/storageclass-accessor-webhook/certs/key.pem']
        ports:
        - containerPort: 443 # change the port as needed
        volumeMounts:
          - name: storageclass-accessor-webhook-certs
            mountPath: /etc/storageclass-accessor-webhook/certs
            readOnly: true
      volumes:
        - name: storageclass-accessor-webhook-certs
          secret:
            secretName: accessor-validation-secret
      serviceAccountName: storageclass-accessor
      serviceAccount: storageclass-accessor
---
apiVersion: v1
kind: Service
metadata:
  name: storageclass-accessor-service
  namespace: default # NOTE: change the namespace
spec:
  selector:
    app: storageclass-accessor
  ports:
    - protocol: TCP
      port: 443 # Change if needed
      targetPort: 443 # Change if the webserver image expects a different port
